name: Check build
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/onionui/miyoomini-toolchain:latest
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Docker client
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get -y install --no-install-recommends docker.io
    - name: Build
      shell: bash
      run: |
        make with-toolchain CMD=build
