name: Check build
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/onionui/miyoomini-toolchain:latest
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Inspect folder
      run: pwd -P; ls -lah
    - name: Build
      shell: bash
      run: |
        source /root/.bashrc
        make build
